version: '3.9'
services:
  frontend:
    build: .
    networks:
      - lambda-local
    volumes:
      - ./:/app
    ports:
      - 3000:3000
        

networks:
  lambda-local:
    external: true
    name: lambda-local

